// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7bt04wBfuKKvQQKJjpdL7pWS_bbI838',
    appId: '1:678869600841:web:7bb649ab0f9287d32e0d98',
    messagingSenderId: '678869600841',
    projectId: 'payroll-f5ba7',
    authDomain: 'payroll-f5ba7.firebaseapp.com',
    storageBucket: 'payroll-f5ba7.appspot.com',
    measurementId: 'G-CL7CTFSQ9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC659ld3y2_xxzLKHabrILuR6WHiDHZ-3I',
    appId: '1:678869600841:android:219f221be3fcd1c52e0d98',
    messagingSenderId: '678869600841',
    projectId: 'payroll-f5ba7',
    storageBucket: 'payroll-f5ba7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9_KEApx-mZhGP5T2rGlH-rdSqrS4hcb4',
    appId: '1:678869600841:ios:1741b846713214d82e0d98',
    messagingSenderId: '678869600841',
    projectId: 'payroll-f5ba7',
    storageBucket: 'payroll-f5ba7.appspot.com',
    iosClientId: '678869600841-05hdqk3qehnfbvb18q42val3u3vu42t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.payrollApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9_KEApx-mZhGP5T2rGlH-rdSqrS4hcb4',
    appId: '1:678869600841:ios:1741b846713214d82e0d98',
    messagingSenderId: '678869600841',
    projectId: 'payroll-f5ba7',
    storageBucket: 'payroll-f5ba7.appspot.com',
    iosClientId: '678869600841-05hdqk3qehnfbvb18q42val3u3vu42t7.apps.googleusercontent.com',
    iosBundleId: 'com.example.payrollApp',
  );
}
